using System.Runtime.InteropServices;
using Windows.Win32.Foundation;
using Windows.Win32.Security;
using Windows.Win32.System.Threading;

namespace SparkerSystemService;

public static class Native
{
  // The function signature generated by CsWin32 does not accept an lpStartupInfo parameter of type STARTUPINFOEXW*
  [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
  internal static extern unsafe BOOL CreateProcessW(
    PCWSTR lpApplicationName,
    PWSTR lpCommandLine,
    SECURITY_ATTRIBUTES* lpProcessAttributes,
    SECURITY_ATTRIBUTES* lpThreadAttributes,
    BOOL bInheritHandles,
    PROCESS_CREATION_FLAGS dwCreationFlags,
    void* lpEnvironment,
    PCWSTR lpCurrentDirectory,
    STARTUPINFOEXW* lpStartupInfo,
    PROCESS_INFORMATION* lpProcessInformation
  );
  
  [DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
  internal static extern unsafe BOOL CreateProcessAsUserW(
    HANDLE hToken,
    PCWSTR lpApplicationName,
    PWSTR lpCommandLine,
    SECURITY_ATTRIBUTES* lpProcessAttributes,
    SECURITY_ATTRIBUTES* lpThreadAttributes,
    BOOL bInheritHandles,
    PROCESS_CREATION_FLAGS dwCreationFlags,
    void* lpEnvironment,
    PCWSTR lpCurrentDirectory,
    STARTUPINFOEXW* lpStartupInfo,
    PROCESS_INFORMATION* lpProcessInformation
  );
  
  [DllImport("kernel32.dll", SetLastError = true)]
  internal static extern unsafe BOOL InitializeProcThreadAttributeList(
    IntPtr lpAttributeList,
    int dwAttributeCount,
    int dwFlags,
    nuint* lpSize
  );
}